import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.scss";

export default function Home({ users }) {
  const [usersData, setUsersData] = useState([]);
  useEffect(() => {
    if (users) {
      const data = [];
      for (let i = 0; i < 10; i++) {
        data.push({ id: users[i].id, title: users[i].title });
      }
      setUsersData(data);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
          {usersData.map((user) => (
            <li key={user.id}>
              <Link href={`http://localhost:3000/users/${user.id}`}>
                <p>{user.title}</p>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const api = process.env.API_URL || "";
  const response = await fetch(`${api}/todos`);
  const data = await response.json();

  return {
    props: {
      users: data,
    },
  };
}

// export async function getStaticProps() {
//   const response = await fetch(`https://jsonplaceholder.typicode.com/todos`);
//   const data = await response.json();

//   return {
//     props: {
//       users: data,
//     },
//     revalidate: 15
//   };
// }
